data=read.csv(file.choose())
#Select the csv file using the pop-up window
View(data)
attach(data)
head(data)
names
#Taking only the Numerical variables.
data1=subset(data,select=-c(Brand,Model,FastCharge_KmH,Segment,RapidCharge,PowerTrain,BodyStyle))
View(data1)
summary(data)
attach(data1)
mod1<-lm(PriceEuro~Range_Km,data=data1)
summary(mod1)
mod2<-lm(PriceEuro~AccelSec,data=data1)
summary(mod2)
mod3<-lm(PriceEuro~TopSpeed_KmH,data=data1)
summary(mod3)
mod4<-lm(PriceEuro~Efficiency_WhKm,data=data1)
summary(mod4)
plot(PriceEuro,Range_Km)
plot(PriceEuro,AccelSec)
plot(PriceEuro,Efficiency_WhKm)
plot(PriceEuro,TopSpeed_KmH)
library(ggplot2)
plot1=ggplot(data,aes(Efficiency_WhKm))+geom_density(fill="blue", alpha=0.3)+xlim(100,300)+labs(x="Efficiency",y="Distribution of data")+ggtitle("Distribution of Efficiency")+geom_vline(xintercept = median(Efficiency_WhKm))
plot2=ggplot(data,aes(Range_Km))+geom_density(fill="blue", alpha=0.3)+xlim(-100,1100)+labs(x="Range",y="Distribution of data")+ggtitle("Distribution of Range")+geom_vline(xintercept = median(Range_Km))
plot3=ggplot(data,aes(TopSpeed_KmH))+geom_density(fill="blue", alpha=0.3)+xlim(0,500)+labs(x="TopSpeed",y="Distribution of data")+ggtitle("Distribution of TopSpeed")+geom_vline(xintercept = median(TopSpeed_KmH))
plot4=ggplot(data,aes(PriceEuro))+geom_density(fill="blue", alpha=0.3)+labs(x="Price",y="Distribution of data")+ggtitle("Distribution of Price")+geom_vline(xintercept = median(PriceEuro))+xlim(0,150000)
plot1;plot2;plot3;plot4
library(ggcorrplot)
cor=cor(data1)
View(cor)
library(wesanderson)
ggcorrplot(cor,colors = wes_palette(name="Darjeeling2",5),lab = T,lab_col="white",lab_size=3,ggtheme = ggplot2::theme_light(),hc.order = T)
mod<-lm(log(PriceEuro)~Range_Km+AccelSec+TopSpeed_KmH+Efficiency_WhKm,data=data1)
summary(mod)
# Testing for the assumptions of Multiple Linear Regression using Diagnostic Plots
par(mfrow=c(2,2))
plot(mod)
car::outlierTest(mod)
data2=data1[-c(36,42),]
mod<-lm(log(PriceEuro)~Range_Km+TopSpeed_KmH+Efficiency_WhKm,data=data2)
summary(mod)
plot(mod)
car::outlierTest(mod)
data3=data2[-c(1,55),]
mod<-lm(log(PriceEuro)~Range_Km+TopSpeed_KmH+Efficiency_WhKm,data=data3)
summary(mod)
plot(mod)
#Testing for Multicollinearity
#Variance Inflation factor
car::vif(mod)
data4=subset(data3,select = -c(AccelSec,TopSpeed_KmH))
mod<-lm(log(PriceEuro)~Range_Km+Efficiency_WhKm+TopSpeed_KmH,data=data3)
summary(mod)
plot(mod)
#Test for Multicollinearity
lmtest::bptest(mod)
#Test for Autocorrelation
car::durbinWatsonTest(mod)
